AWSTemplateFormatVersion: 2010-09-09
Description: Enable Config Service
Resources:
  ConfigBucket:
    DeletionPolicy: Retain
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub 'config-bucket-${AWS::AccountId}'

  ConfigBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref ConfigBucket
      Name: !Sub 'config-bucket-policy-${AWS::AccountId}'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AWSConfigBucketPermissionsCheck
            Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action: 's3:GetBucketAcl'
            Resource:
              - !Sub 'arn:aws:s3:::${ConfigBucket}'
          - Sid: AWSConfigBucketDelivery
            Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action: 's3:PutObject'
            Resource:
              - !Sub 'arn:aws:s3:::${ConfigBucket}/AWSLogs/${AWS::AccountId}/*'

  ConfigRecorderRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - config.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSConfigRole'
      Name: !Sub 'config-recorder-role-${AWS::AccountId}'
      Path: /

  ConfigRecorder:
    Type: 'AWS::Config::ConfigurationRecorder'
    DependsOn:
      - ConfigBucketPolicy
    Properties:
      RoleARN: !GetAtt ConfigRecorderRole.Arn
      RecordingGroup:
        AllSupported: true
        IncludeGlobalResourceTypes: !Equals
          - !Ref 'AWS::Region'
          - us-east-1

  ConfigDeliveryChannel:
    Type: 'AWS::Config::DeliveryChannel'
    DependsOn:
      - ConfigBucketPolicy
    Properties:
      ConfigSnapshotDeliveryProperties:
        DeliveryFrequency: 24hours
      S3BucketName: !Ref ConfigBucket
